# Generated by Django 6.0.6 on 2026-07-26 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitos',
            fields=[
                ('id_hito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hito', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimado', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Planificada'), ('en_progreso', 'En Ejecucion'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('avance_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='hitos/')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_obra', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimado', models.DateField()),
                ('presupuesto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('plano', models.FileField(blank=True, null=True, upload_to='planos/')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('En_ejecucion', 'En Ejecucion'), ('finalizada', 'Finalizada'), ('suspendida', 'Suspendida')], default='planificada', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria_Pesada',
            fields=[
                ('id_maquinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_maquinaria', models.CharField(max_length=50, unique=True)),
                ('tipo_maquinaria', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinaria/')),
                ('id_hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.hitos')),
                ('obra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.obra')),
            ],
        ),
        migrations.AddField(
            model_name='hitos',
            name='obra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.obra'),
        ),
        migrations.CreateModel(
            name='Cuadrilla_Trabajo',
            fields=[
                ('id_cuadrilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuadrilla', models.CharField(max_length=50, unique=True)),
                ('tipo_trabajo', models.CharField(max_length=50, unique=True)),
                ('cantidad_trabajadores', models.IntegerField()),
                ('obra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Avances',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('avance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reporte', models.FileField(blank=True, null=True, upload_to='avances/')),
                ('hito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.hitos')),
            ],
        ),
        migrations.CreateModel(
            name='Subcontratista',
            fields=[
                ('id_subcontratista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('obra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.obra')),
            ],
        ),
    ]
