# Generated by Django 6.0.6 on 2026-07-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstruccionObras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='presupuesto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
