# Generated by Django 6.0.6 on 2026-07-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstruccionObras', '0002_alter_obra_presupuesto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('Planificada', 'Planificada'), ('En ejecucion', 'En Ejecucion'), ('Finalizada', 'Finalizada'), ('Suspendida', 'Suspendida')], default='planificada', max_length=20),
        ),
    ]
