# Generated by Django 6.0.6 on 2026-07-26 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstruccionObras', '0004_alter_obra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria_pesada',
            name='id_hito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.hitos'),
        ),
    ]
