# Generated by Django 6.0.6 on 2026-07-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstruccionObras', '0005_alter_maquinaria_pesada_id_hito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completado', 'Completado')], default='Pendiente', max_length=20),
        ),
    ]
