# Generated by Django 6.0.6 on 2026-07-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstruccionObras', '0006_alter_hitos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialObra',
            fields=[
                ('id_material_obra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_estimada', models.FloatField()),
                ('cantidad_real', models.FloatField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.material')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConstruccionObras.obra')),
            ],
        ),
    ]
