# Generated by Django 6.0.6 on 2026-07-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstruccionObras', '0007_material_materialobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria_pesada',
            name='id_hito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConstruccionObras.hitos'),
        ),
        migrations.AlterField(
            model_name='maquinaria_pesada',
            name='obra_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConstruccionObras.obra'),
        ),
    ]
