# Generated by Django 6.0.6 on 2026-07-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConstruccionObras', '0008_alter_maquinaria_pesada_id_hito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria_pesada',
            name='nombre_maquinaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maquinaria_pesada',
            name='tipo_maquinaria',
            field=models.CharField(max_length=50),
        ),
    ]
